GOENV: DEV
SRV_TRANSFER__BoltStorage_BoltFileName: data.db
SRV_TRANSFER__BoltStorage_BoltFilePath: bolt
SRV_TRANSFER__BoltStorage_BoltStoragePath: /Users/ryan/Desktop/experiment_code/mysql-transfer/store/data
SRV_TRANSFER__BoltStorage_PositionBucket: Position
SRV_TRANSFER__BoltStorage_PositionKey: bolt_position_key
SRV_TRANSFER__BoltStorage_RowRequestBucket: RowRequest
SRV_TRANSFER__BoltStorage_TaskBucket: Task
SRV_TRANSFER__Canal_BinlogFileName: mysql-bin.000001
SRV_TRANSFER__Canal_BinlogPosition: "1"
SRV_TRANSFER__Canal_Databases_0: binlog_test
SRV_TRANSFER__Canal_Host: 127.0.0.1
SRV_TRANSFER__Canal_Password: OKpeng5699121@
SRV_TRANSFER__Canal_Port: "3306"
SRV_TRANSFER__Canal_Tables_0: user
SRV_TRANSFER__Canal_Tables_1: user1
SRV_TRANSFER__Canal_UseBoltStoragePosition: "false"
SRV_TRANSFER__Canal_User: root
SRV_TRANSFER__HandlerRowEventPoolSize: "20"
SRV_TRANSFER__Log_Level: DEBUG
SRV_TRANSFER__Log_Output: Always
